version: "3.9"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
  web:
    build: ../backend
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ../backend:/backend
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
  redis:
    image: "redis:alpine"
  celery:
    build: ../backend
    command: celery -A backend_project worker -l info
    volumes:
      - ../backend:/backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
  celery-beat:
    build: ../backend
    command: celery -A backend_project beat -l info
    volumes:
      - ../backend:/backend
    env_file:
      - .env
    depends_on:
      - db
      - redis


volumes:
  postgres_data: