# Generated by Django 3.1.7 on 2021-03-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maradmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('url_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Maradmin',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('maradmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_api.maradmin')),
            ],
            options={
                'verbose_name': 'Body',
            },
        ),
    ]
