# Generated by Django 3.1.7 on 2021-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20210307_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maradmin',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
