# Generated by Django 3.1.7 on 2021-10-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_auto_20211021_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maradmin',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
